using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace ShipStation.Models
{
    public class ShipStationOrder
    {
        /// <summary>
        /// A user-defined order number used to identify an order.
        /// string, required, max-length: 50
        /// </summary>
        [JsonProperty("orderNumber")]
        public string OrderNumber { get; set; }

        /// <summary>
        /// A user-provided key that should be unique to each order.
        /// If an orderKey is not provided, ShipStation will create a new order and generate a unique orderKey for that order.
        /// If the orderKey is provided, the createorder method will either: create a new order if the provided orderKey is not found,
        /// or, update the existing order if the orderKey is found.
        /// string, optional
        /// </summary>
        [JsonProperty("orderKey")]
        public string OrderKey { get; set; }

        /// <summary>
        /// The date the order was placed.
        /// string, required
        /// </summary>
        [JsonProperty("orderDate")]
        public string OrderDate { get; set; }

        /// <summary>
        /// The date the order was paid for.
        /// string, optional
        /// </summary>
        [JsonProperty("paymentDate")]
        public string PaymentDate { get; set; }

        [JsonProperty("modifyDate")]
        public string ModifyDate { get; set; }

        /// <summary>
        /// The date the order is to be shipped before or on.
        /// This field is a suggested value generated by the order source/platform/cart and passed to ShipStation.
        /// string, optional
        /// </summary>
        [JsonProperty("shipByDate")]
        public string ShipByDate { get; set; }

        /// <summary>
        /// The order's status. Possible values: awaiting_payment, awaiting_shipment, shipped, on_hold, cancelled
        /// string, required
        /// </summary>
        [JsonProperty("orderStatus")]
        public string OrderStatus { get; set; }

        /// <summary>
        /// Unique identifier for the customer. Generated by ShipStation the first time the customer record is created. Read-Only
        /// </summary>
        [JsonProperty("customerId")]
        public long? CustomerId { get; set; }

        /// <summary>
        /// The customer's username. Note: This property needs to be defined in order to generate a customer profile
        /// string, optional
        /// </summary>
        [JsonProperty("customerUsername")]
        public string CustomerUsername { get; set; }

        /// <summary>
        /// The customer's email address.
        /// string, optional
        /// </summary>
        [JsonProperty("customerEmail")]
        public string CustomerEmail { get; set; }

        /// <summary>
        /// The recipients billing address. Use the Address model.
        /// Address, required
        /// </summary>
        [JsonProperty("billTo")]
        public ToAddress BillTo { get; set; }

        /// <summary>
        /// The recipient's shipping address. Use the Address model.
        /// Address, required
        /// </summary>
        [JsonProperty("shipTo")]
        public ToAddress ShipTo { get; set; }

        /// <summary>
        /// An array of item objects. Use an array of OrderItem models.
        /// OrderItem, optional
        /// </summary>
        [JsonProperty("items")]
        public List<OrderItem> Items { get; set; }

        /// <summary>
        /// The total amount paid for the Order.
        /// number, optional
        /// </summary>
        [JsonProperty("amountPaid")]
        public double AmountPaid { get; set; }

        /// <summary>
        /// The total tax amount for the Order.
        /// number, optional
        /// </summary>
        [JsonProperty("taxAmount")]
        public double TaxAmount { get; set; }

        /// <summary>
        /// Shipping amount paid by the customer, if any.
        /// number, optional
        /// </summary>
        [JsonProperty("shippingAmount")]
        public double ShippingAmount { get; set; }

        /// <summary>
        /// Notes left by the customer when placing the order.
        /// string, optional
        /// </summary>
        [JsonProperty("customerNotes")]
        public string CustomerNotes { get; set; }

        /// <summary>
        /// Private notes that are only visible to the seller.
        /// string, optional
        /// </summary>
        [JsonProperty("internalNotes")]
        public string InternalNotes { get; set; }

        /// <summary>
        /// Specifies whether or not this Order is a gift
        /// boolean, optional
        /// </summary>
        [JsonProperty("gift")]
        public bool? Gift { get; set; }

        /// <summary>
        /// Gift message left by the customer when placing the order.
        /// string, optional
        /// </summary>
        [JsonProperty("giftMessage")]
        public string GiftMessage { get; set; }

        /// <summary>
        /// Method of payment used by the customer.
        /// string, optional
        /// </summary>
        [JsonProperty("paymentMethod")]
        public string PaymentMethod { get; set; }

        /// <summary>
        /// Identifies the shipping service selected by the customer when placing this order.
        /// This value is given to ShipStation by the marketplace/cart and helps identify
        /// what shipping service the customer selected upon checkout.
        /// string, optional
        /// </summary>
        [JsonProperty("requestedShippingService")]
        public string RequestedShippingService { get; set; }

        /// <summary>
        /// The code for the carrier that is to be used(or was used) when this order is shipped(was shipped).
        /// string, optional
        /// </summary>
        [JsonProperty("carrierCode")]
        public string CarrierCode { get; set; }

        /// <summary>
        /// The code for the shipping service that is to be used(or was used) when this order is shipped(was shipped).
        /// string, optional
        /// </summary>
        [JsonProperty("serviceCode")]
        public string ServiceCode { get; set; }

        /// <summary>
        /// The code for the package type that is to be used(or was used) when this order is shipped(was shipped).
        /// string, optional
        /// </summary>
        [JsonProperty("packageCode")]
        public string PackageCode { get; set; }

        /// <summary>
        /// The type of delivery confirmation that is to be used(or was used) when this order is shipped(was shipped).
        /// Possible values: none, delivery, signature, adult_signature, and direct_signature. direct_signature is available for FedEx only.
        /// string, optional
        /// </summary>
        [JsonProperty("confirmation")]
        public string Confirmation { get; set; }

        /// <summary>
        /// The date the order was shipped.
        /// string, optional
        /// </summary>
        [JsonProperty("shipDate")]
        public string ShipDate { get; set; }

        /// <summary>
        /// Weight of the order. Use the Weight model.
        /// Weight, optional
        /// </summary>
        [JsonProperty("weight")]
        public Weight Weight { get; set; }

        /// <summary>
        /// Dimensions of the order. Use the Dimensions model.
        /// Dimensions, optional
        /// </summary>
        [JsonProperty("dimensions")]
        public Dimensions Dimensions { get; set; }

        /// <summary>
        /// The shipping insurance information associated with this order. Use the InsuranceOptions model.
        /// InsuranceOptions, optional
        /// </summary>
        [JsonProperty("insuranceOptions")]
        public InsuranceOptions InsuranceOptions { get; set; }

        /// <summary>
        /// Customs information that can be used to generate customs documents for international orders. Use the InternationalOptions model.
        /// InternationalOptions, optional
        /// </summary>
        [JsonProperty("internationalOptions")]
        public InternationalOptions InternationalOptions { get; set; }

        /// <summary>
        /// Various advanced options that may be available depending on the shipping carrier that is used to ship the order. Use the AdvancedOptions model.
        /// AdvancedOptions, optional
        /// </summary>
        [JsonProperty("advancedOptions")]
        public AdvancedOptions AdvancedOptions { get; set; }

        /// <summary>
        /// Array of tagIds. Each tagId identifies a tag that has been associated with this order.
        /// number[]
        /// </summary>
        [JsonProperty("tagIds")]
        public List<long> TagIds { get; set; }
    }

    public class AdvancedOptions
    {
        /// <summary>
        /// Specifies the warehouse where to the order is to ship from. If the order was fulfilled using a fill provider,
        /// no warehouse is attached to these orders and will result in a null value being returned.
        /// </summary>
        [JsonProperty("warehouseId")]
        public long WarehouseId { get; set; }

        /// <summary>
        /// Specifies whether the order is non-machinable.
        /// </summary>
        [JsonProperty("nonMachinable")]
        public bool NonMachinable { get; set; }

        /// <summary>
        /// Specifies whether the order is to be delivered on a Saturday.
        /// </summary>
        [JsonProperty("saturdayDelivery")]
        public bool SaturdayDelivery { get; set; }

        /// <summary>
        /// Specifies whether the order contains alcohol.
        /// </summary>
        [JsonProperty("containsAlcohol")]
        public bool ContainsAlcohol { get; set; }

        /// <summary>
        /// Read-Only: Returns whether or not an order has been merged or split with another order. Read Only
        /// </summary>
        [JsonProperty("mergedOrSplit")]
        public bool MergedOrSplit { get; set; }

        /// <summary>
        /// Read-Only: Array of orderIds. Each orderId identifies an order that was merged with the associated order. Read Only
        /// </summary>
        [JsonProperty("mergedIds")]
        public List<long> MergedIds { get; set; }

        /// <summary>
        /// Read-Only: If an order has been split, it will return the Parent ID of the order with which it has been split.
        /// If the order has not been split, this field will return null. Read Only
        /// </summary>
        [JsonProperty("parentId")]
        public long? ParentId { get; set; }

        /// <summary>
        /// ID of store that is associated with the order. If not specified in the CreateOrder call either to create or update an order,
        /// ShipStation will default to the first manual store on the account. Can only be specified during order creation.
        /// </summary>
        [JsonProperty("storeId")]
        public long StoreId { get; set; }

        /// <summary>
        /// Field that allows for custom data to be associated with an order
        /// </summary>
        [JsonProperty("customField1")]
        public string CustomField1 { get; set; }

        /// <summary>
        /// Field that allows for custom data to be associated with an order
        /// </summary>
        [JsonProperty("customField2")]
        public string CustomField2 { get; set; }

        /// <summary>
        /// Field that allows for custom data to be associated with an order
        /// </summary>
        [JsonProperty("customField3")]
        public Uri CustomField3 { get; set; }

        /// <summary>
        /// Identifies the original source/marketplace of the order
        /// </summary>
        [JsonProperty("source")]
        public string Source { get; set; }

        /// <summary>
        /// dentifies which party to bill. Possible values: "my_account", "my_other_account" (see note below), "recipient", "third_party". 
        /// billTo values can only be used when creating/updating orders.
        /// </summary>
        [JsonProperty("billToParty")]
        public string BillToParty { get; set; }

        /// <summary>
        /// Account number of billToParty. billTo values can only be used when creating/updating orders.
        /// </summary>
        [JsonProperty("billToAccount")]
        public string BillToAccount { get; set; }

        /// <summary>
        /// Postal Code of billToParty. billTo values can only be used when creating/updating orders.
        /// </summary>
        [JsonProperty("billToPostalCode")]
        public string BillToPostalCode { get; set; }

        /// <summary>
        /// Country Code of billToParty. billTo values can only be used when creating/updating orders.
        /// </summary>
        [JsonProperty("billToCountryCode")]
        public string BillToCountryCode { get; set; }

        /// <summary>
        /// When using my_other_account billToParty value, the shippingProviderId value associated with the desired account. 
        /// Make a List Carriers call to obtain shippingProviderId values.
        /// </summary>
        [JsonProperty("billToMyOtherAccount")]
        public string BillToMyOtherAccount { get; set; }
    }

    public class ToAddress
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("company")]
        public string Company { get; set; }

        [JsonProperty("street1")]
        public string Street1 { get; set; }

        [JsonProperty("street2")]
        public string Street2 { get; set; }

        [JsonProperty("street3")]
        public object Street3 { get; set; }

        [JsonProperty("city")]
        public string City { get; set; }

        [JsonProperty("state")]
        public string State { get; set; }

        [JsonProperty("postalCode")]
        public string PostalCode { get; set; }

        [JsonProperty("country")]
        public string Country { get; set; }

        [JsonProperty("phone")]
        public string Phone { get; set; }

        [JsonProperty("residential")]
        public bool? Residential { get; set; }
    }

    public class Dimensions
    {
        [JsonProperty("units")]
        public string Units { get; set; }

        [JsonProperty("length")]
        public long Length { get; set; }

        [JsonProperty("width")]
        public long Width { get; set; }

        [JsonProperty("height")]
        public long Height { get; set; }
    }

    public class InsuranceOptions
    {
        [JsonProperty("provider")]
        public string Provider { get; set; }

        [JsonProperty("insureShipment")]
        public bool InsureShipment { get; set; }

        [JsonProperty("insuredValue")]
        public long InsuredValue { get; set; }
    }

    public class InternationalOptions
    {
        /// <summary>
        /// Contents of international shipment. Available options are: "merchandise", "documents", "gift", "returned_goods", or "sample"
        /// </summary>
        [JsonProperty("contents")]
        public object Contents { get; set; }

        /// <summary>
        /// An array of customs items.
        /// NOTE: To supply customsItems in the CreateOrder call and have the values not be overwritten by ShipStation, you must set the International Settings > Customs Declarations to "Leave blank (Enter Manually)" in the UI: https://ss.shipstation.com/#/settings/international
        /// Please see our ShipStation's International Settings KB article to learn how to make this change in the UI.
        /// </summary>
        [JsonProperty("customsItems")]
        public CustomsItems CustomsItems { get; set; }

        /// <summary>
        /// Non-Delivery option for international shipment. Available options are: "return_to_sender" or "treat_as_abandoned".
        /// NOTE: If the shipment is created through the Orders/CreateLabelForOrder endpoint and the nonDelivery field is not specified then value defaults based on the International Setting in the UI.If the call is being made to the Shipments/CreateLabel endpoint and the nonDelivery field is not specified then the value will default to "return_to_sender".
        /// </summary>
        [JsonProperty("nonDelivery")]
        public string NonDelivery { get; set; }
    }

    public class OrderItem
    {
        /// <summary>
        /// An identifier for the OrderItem in the originating system.
        /// </summary>
        [JsonProperty("lineItemKey")]
        public string LineItemKey { get; set; }

        /// <summary>
        /// The SKU (stock keeping unit) identifier for the product associated with this line item.
        /// </summary>
        [JsonProperty("sku")]
        public string Sku { get; set; }

        /// <summary>
        /// The name of the product associated with this line item. Cannot be null
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>
        /// The public URL to the product image.
        /// </summary>
        [JsonProperty("imageUrl")]
        public object ImageUrl { get; set; }

        /// <summary>
        /// The weight of a single item.
        /// </summary>
        [JsonProperty("weight")]
        public Weight Weight { get; set; }

        /// <summary>
        /// The quantity of product ordered.
        /// </summary>
        [JsonProperty("quantity")]
        public long Quantity { get; set; }

        /// <summary>
        /// The sell price of a single item specified by the order source.
        /// </summary>
        [JsonProperty("unitPrice")]
        public double UnitPrice { get; set; }

        /// <summary>
        /// The tax price of a single item specified by the order source.
        /// </summary>
        [JsonProperty("taxAmount")]
        public double? TaxAmount { get; set; }

        /// <summary>
        /// The shipping amount or price of a single item specified by the order source.
        /// </summary>
        [JsonProperty("shippingAmount")]
        public double? ShippingAmount { get; set; }

        /// <summary>
        /// The location of the product within the seller's warehouse (e.g. Aisle 3, Shelf A, Bin 5)
        /// </summary>
        [JsonProperty("warehouseLocation")]
        public string WarehouseLocation { get; set; }

        /// <summary>
        /// Item Option
        /// </summary>
        [JsonProperty("options")]
        public List<Option> Options { get; set; }

        /// <summary>
        /// The identifier for the Product Resource associated with this OrderItem.
        /// </summary>
        [JsonProperty("productId")]
        public string ProductId { get; set; }

        /// <summary>
        /// The fulfillment SKU associated with this OrderItem if the fulfillment provider requires an identifier other then the SKU.
        /// </summary>
        [JsonProperty("fulfillmentSku")]
        public string FulfillmentSku { get; set; }

        /// <summary>
        /// Indicates that the OrderItem is a non-physical adjustment to the order (e.g. a discount or promotional code)
        /// </summary>
        [JsonProperty("adjustment")]
        public bool Adjustment { get; set; }

        /// <summary>
        /// The Universal Product Code associated with this OrderItem.
        /// </summary>
        [JsonProperty("upc")]
        public string Upc { get; set; }
    }

    public class Option
    {
        /// <summary>
        /// Name of item option. Example: "Size"
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>
        /// The value of the item option. Example: "Medium"
        /// </summary>
        [JsonProperty("value")]
        public string Value { get; set; }
    }

    public class Weight
    {
        /// <summary>
        /// weight value.
        /// </summary>
        [JsonProperty("value")]
        public double Value { get; set; }

        /// <summary>
        /// units of weight. Allowed units are: "pounds", "ounces", or "grams"
        /// </summary>
        [JsonProperty("units")]
        public string Units { get; set; }

        /// <summary>
        /// (read only) A numeric value that is equivalent to the above units field.
        /// </summary>
        [JsonProperty("WeightUnits")]
        public long WeightUnits { get; set; }
    }

    public class CustomsItems
    {
        /// <summary>
        /// Read Only field. When this field is not submitted in the Order/CreateOrder call, it will create a new customs line.
        /// If this field is included when submitting an order through Order/CreateOrder, then it will look for the corresponding customs line and update any values.
        /// </summary>
        [JsonProperty("customsItemId")]
        public string CustomsItemId { get; set; }

        /// <summary>
        /// A short description of the CustomsItem
        /// </summary>
        [JsonProperty("description")]
        public string Description { get; set; }

        /// <summary>
        /// The quantity for this line item
        /// </summary>
        [JsonProperty("quantity")]
        public long Quantity { get; set; }

        /// <summary>
        /// The value (in USD) of the line item
        /// </summary>
        [JsonProperty("value")]
        public long Value { get; set; }

        /// <summary>
        /// The Harmonized Commodity Code for this line item
        /// </summary>
        [JsonProperty("harmonizedTariffCode")]
        public string HarmonizedTariffCode { get; set; }

        /// <summary>
        /// The 2-character ISO country code where the item originated
        /// </summary>
        [JsonProperty("countryOfOrigin")]
        public string CountryOfOrigin { get; set; }
    }
}
